export const OPERATION_CATALOG = [
  {
    tag: 'API Keys',
    operationId: 'listApiKeys',
    method: 'get',
    path: '/api-keys',
    sdkMethod: 'client.apiKeys.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'API Keys',
    operationId: 'createApiKey',
    method: 'post',
    path: '/api-keys',
    sdkMethod: 'client.apiKeys.create',
    responseStatus: 200,
  },
  {
    tag: 'API Keys',
    operationId: 'deleteApiKey',
    method: 'delete',
    path: '/api-keys/{id}',
    sdkMethod: 'client.apiKeys.del',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'listDocuments',
    method: 'get',
    path: '/documents',
    sdkMethod: 'client.documents.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Documents',
    operationId: 'createDocument',
    method: 'post',
    path: '/documents',
    sdkMethod: 'client.documents.create',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'createDocumentBootstrap',
    method: 'post',
    path: '/documents/bootstrap',
    sdkMethod: 'client.documents.bootstrap',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'getDocument',
    method: 'get',
    path: '/documents/{sessionId}',
    sdkMethod: 'client.documents.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'updateDocument',
    method: 'put',
    path: '/documents/{sessionId}',
    sdkMethod: 'client.documents.update',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'deleteDocument',
    method: 'delete',
    path: '/documents/{sessionId}',
    sdkMethod: 'client.documents.del',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'listEpochs',
    method: 'get',
    path: '/documents/{sessionId}/epochs',
    sdkMethod: 'client.documents.epochs.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Documents',
    operationId: 'getEpoch',
    method: 'get',
    path: '/documents/{sessionId}/epochs/{epoch}',
    sdkMethod: 'client.documents.epochs.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'listFeedEntries',
    method: 'get',
    path: '/documents/{sessionId}/feed-entries',
    sdkMethod: 'client.documents.feedEntries.list',
    responseStatus: 200,
    pagination: 'limit + nextPageToken',
  },
  {
    tag: 'Documents',
    operationId: 'listLinks',
    method: 'get',
    path: '/documents/{sessionId}/links',
    sdkMethod: 'client.documents.links.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Documents',
    operationId: 'listPendingActions',
    method: 'get',
    path: '/documents/{sessionId}/pending-actions',
    sdkMethod: 'client.documents.pendingActions.list',
    responseStatus: 200,
  },
  {
    tag: 'Documents',
    operationId: 'resumeDocumentProcessing',
    method: 'post',
    path: '/documents/{sessionId}/resume',
    sdkMethod: 'client.documents.resume',
    responseStatus: 202,
  },
  {
    tag: 'Documents',
    operationId: 'stopDocumentProcessing',
    method: 'post',
    path: '/documents/{sessionId}/stop',
    sdkMethod: 'client.documents.stop',
    responseStatus: 202,
  },
  {
    tag: 'Documents',
    operationId: 'runOperation',
    method: 'post',
    path: '/documents/{sessionId}/{operation}',
    sdkMethod: 'client.documents.runOperation',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'listTimelines',
    method: 'get',
    path: '/timelines',
    sdkMethod: 'client.timelines.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Timelines',
    operationId: 'createTimeline',
    method: 'post',
    path: '/timelines',
    sdkMethod: 'client.timelines.create',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'getTimeline',
    method: 'get',
    path: '/timelines/{timeline}',
    sdkMethod: 'client.timelines.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'deleteTimeline',
    method: 'delete',
    path: '/timelines/{timeline}',
    sdkMethod: 'client.timelines.del',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'getTimelineEntries',
    method: 'get',
    path: '/timelines/{timeline}/entries',
    sdkMethod: 'client.timelines.entries.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Timelines',
    operationId: 'createTimelineEntry',
    method: 'post',
    path: '/timelines/{timeline}/entries',
    sdkMethod: 'client.timelines.entries.create',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'getTimelineEntry',
    method: 'get',
    path: '/timelines/{timeline}/entries/{entryId}',
    sdkMethod: 'client.timelines.entries.retrieve',
    responseStatus: 202,
  },
  {
    tag: 'Timelines',
    operationId: 'listTimelinePermissions',
    method: 'get',
    path: '/timelines/{timeline}/permissions',
    sdkMethod: 'client.timelines.permissions.list',
    responseStatus: 200,
    pagination: 'nextPageToken',
  },
  {
    tag: 'Timelines',
    operationId: 'createTimelinePermission',
    method: 'post',
    path: '/timelines/{timeline}/permissions',
    sdkMethod: 'client.timelines.permissions.create',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'getTimelinePermission',
    method: 'get',
    path: '/timelines/{timeline}/permissions/{permissionId}',
    sdkMethod: 'client.timelines.permissions.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Timelines',
    operationId: 'deleteTimelinePermission',
    method: 'delete',
    path: '/timelines/{timeline}/permissions/{permissionId}',
    sdkMethod: 'client.timelines.permissions.del',
    responseStatus: 200,
  },
  {
    tag: 'Me',
    operationId: 'getMyDocuments',
    method: 'get',
    path: '/me/documents',
    sdkMethod: 'client.me.documents.list',
    responseStatus: 200,
    pagination: 'pageSize + nextPageToken',
  },
  {
    tag: 'Me',
    operationId: 'getInbox',
    method: 'get',
    path: '/me/inbox',
    sdkMethod: 'client.me.inbox.list',
    responseStatus: 200,
    pagination: 'pageSize + nextPageToken',
  },
  {
    tag: 'Me',
    operationId: 'listRecentlyUsedDocuments',
    method: 'get',
    path: '/me/recently-used',
    sdkMethod: 'client.me.recentlyUsed.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Me',
    operationId: 'getSearchDocuments',
    method: 'get',
    path: '/me/search/documents',
    sdkMethod: 'client.me.search.documents',
    responseStatus: 200,
    pagination: 'limit + cursor(nextPageToken)',
  },
  {
    tag: 'Me',
    operationId: 'getStarredDocuments',
    method: 'get',
    path: '/me/starred',
    sdkMethod: 'client.me.starred.list',
    responseStatus: 200,
    pagination: 'pageSize + nextPageToken',
  },
  {
    tag: 'Me',
    operationId: 'starDocument',
    method: 'put',
    path: '/me/starred/{sessionId}',
    sdkMethod: 'client.me.starred.add',
    responseStatus: 200,
  },
  {
    tag: 'Me',
    operationId: 'unstarDocument',
    method: 'delete',
    path: '/me/starred/{sessionId}',
    sdkMethod: 'client.me.starred.remove',
    responseStatus: 200,
  },
  {
    tag: 'User',
    operationId: 'getUserData',
    method: 'get',
    path: '/user',
    sdkMethod: 'client.user.get',
    responseStatus: 200,
  },
  {
    tag: 'User',
    operationId: 'updateUserData',
    method: 'post',
    path: '/user',
    sdkMethod: 'client.user.update',
    responseStatus: 200,
  },
  {
    tag: 'User',
    operationId: 'requestPasswordReset',
    method: 'post',
    path: '/user/password/reset/request',
    sdkMethod: 'client.user.password.requestReset',
    responseStatus: 200,
  },
  {
    tag: 'User',
    operationId: 'resetPassword',
    method: 'post',
    path: '/user/password/reset',
    sdkMethod: 'client.user.password.reset',
    responseStatus: 200,
  },
  {
    tag: 'User',
    operationId: 'getUiSettings',
    method: 'get',
    path: '/user/settings/ui',
    sdkMethod: 'client.user.uiSettings.get',
    responseStatus: 200,
  },
  {
    tag: 'User',
    operationId: 'updateUiSettings',
    method: 'post',
    path: '/user/settings/ui',
    sdkMethod: 'client.user.uiSettings.update',
    responseStatus: 200,
  },
  {
    tag: 'Users',
    operationId: 'getUsersByIds',
    method: 'get',
    path: '/users',
    sdkMethod: 'client.users.getByIds',
    responseStatus: 200,
  },
  {
    tag: 'Myos Events',
    operationId: 'listMyOSEvents',
    method: 'get',
    path: '/myos-events',
    sdkMethod: 'client.myOsEvents.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Myos Events',
    operationId: 'getMyOSEvents',
    method: 'get',
    path: '/myos-events/{event}',
    sdkMethod: 'client.myOsEvents.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Webhooks',
    operationId: 'listWebhooks',
    method: 'get',
    path: '/webhooks',
    sdkMethod: 'client.webhooks.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Webhooks',
    operationId: 'createWebhook',
    method: 'post',
    path: '/webhooks',
    sdkMethod: 'client.webhooks.create',
    responseStatus: 200,
  },
  {
    tag: 'Webhooks',
    operationId: 'getWebhook',
    method: 'get',
    path: '/webhooks/{webhookId}',
    sdkMethod: 'client.webhooks.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Webhooks',
    operationId: 'updateWebhook',
    method: 'post',
    path: '/webhooks/{webhookId}',
    sdkMethod: 'client.webhooks.update',
    responseStatus: 200,
  },
  {
    tag: 'Webhooks',
    operationId: 'deleteWebhook',
    method: 'delete',
    path: '/webhooks/{webhookId}',
    sdkMethod: 'client.webhooks.del',
    responseStatus: 200,
  },
  {
    tag: 'Webhooks',
    operationId: 'listWebhookDispatches',
    method: 'get',
    path: '/webhooks/{webhookId}/dispatches',
    sdkMethod: 'client.webhooks.dispatches.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Webhooks',
    operationId: 'getWebhookDispatch',
    method: 'get',
    path: '/webhooks/{webhookId}/dispatches/{eventId}',
    sdkMethod: 'client.webhooks.dispatches.retrieve',
    responseStatus: 200,
  },
  {
    tag: 'Webhooks',
    operationId: 'listWebhookDispatchAttempts',
    method: 'get',
    path: '/webhooks/{webhookId}/dispatches/{eventId}/attempts',
    sdkMethod: 'client.webhooks.dispatches.attempts.list',
    responseStatus: 200,
    pagination: 'itemsPerPage + nextPageToken',
  },
  {
    tag: 'Webhooks',
    operationId: 'resendWebhook',
    method: 'post',
    path: '/webhooks/{webhookId}/resend',
    sdkMethod: 'client.webhooks.resend',
    responseStatus: 200,
  },
  {
    tag: 'Integrations',
    operationId: 'getChatPgtConnector',
    method: 'get',
    path: '/integrations/connectors/chatpgt',
    sdkMethod: 'client.integrations.chatpgt.get',
    responseStatus: 200,
  },
  {
    tag: 'Integrations',
    operationId: 'installChatPgtConnector',
    method: 'post',
    path: '/integrations/connectors/chatpgt/install',
    sdkMethod: 'client.integrations.chatpgt.install',
    responseStatus: 200,
  },
  {
    tag: 'Maintenance',
    operationId: 'cleanupIdempotency',
    method: 'post',
    path: '/maintenance/idempotency/cleanup',
    sdkMethod: 'client.maintenance.cleanupIdempotency',
    responseStatus: 200,
    systemGated: true,
  },
  {
    tag: 'Maintenance',
    operationId: 'flushOutbox',
    method: 'post',
    path: '/maintenance/idempotency/outbox',
    sdkMethod: 'client.maintenance.flushOutbox',
    responseStatus: 200,
    systemGated: true,
  },
  {
    tag: 'Maintenance',
    operationId: 'createExpiredIdempotency',
    method: 'post',
    path: '/maintenance/test-data/expired-idempotency',
    sdkMethod: 'client.maintenance.createExpiredIdempotency',
    responseStatus: 200,
    systemGated: true,
  },
];
